<?php
/**
 * Created by PhpStorm.
 * User: lex
 * Date: 02.03.17
 * Time: 17:56
 */

namespace common\components\klbase;

use yii\web\AssetBundle;

class KlbaseFieldWidgetAsset extends AssetBundle
{
    public $isSelect2 = true;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if( $this->isSelect2 ){
            $this->css[] = 'dist/css/select2.min.css';
            $this->js[] = 'dist/js/select2.full.min.js';
            $this->js[] = 'dist/js/i18n/ru.js';
        }

    }

    public $sourcePath = '@vendor/bower/select2';
    public $baseUrl = '@web';

    public $css = [];

    public $js = [];

    public $depends = [];

}